# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cody Zuschlag
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Senior software engineer with 10 years industry experience
  and a passion for all things node.js.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: codyus
github_username:  codyzu

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

exclude: [vendor, '*/node_modules']

dark_page: false
dark_header: true
