<html>
  <head>
    <title>{{ page.title }}</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
  </head>
  <body>
    <div class="container">
      {{ content }}
    </div>
  </body>
</html>
